package:
  name: ghm
  version: "3.1"

source:
  fn: ghm-3.1.tgz
  url: https://www.helmholtz-muenchen.de/fileadmin/GENEPI/downloads/ghm-3.1.tgz
  md5: 0cfdc1aa80e7501f4766fa9537f96897

build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]

test:
  commands:
    - echo "q" | ghm

about:
  home: https://www.helmholtz-muenchen.de/en/ige/service/software-download/genehunter-modscore/index.html
  license: https://www.helmholtz-muenchen.de/fileadmin/GENEPI/downloads/COPYRIGHT.ghm.3.1
  summary: A MOD-score analysis in which parametric LOD scores are maximized over the parameters of the trait model
